title                    : "Amazon Clone (CardUI, Animation, Fetch, Search)"
name                     : "Angelo"
description              : "Amazon Clone 작성"
url                      : "https://dev-angelo.github.io/amazon-clone/"
baseurl                  :
